service Calculadora{
   void ping(),
   double suma(1:double num1, 2:double num2),
   double resta(1:double num1, 2:double num2),
   double multiplicacion(1:double num1, 2:double num2),
   double division(1:double num1, 2:double num2),
   double potencia(1:double num1, 2:double num2),
   double raiz(1:double num1),
   double factorial(1:double num1),
   double sen(1:double num1),
   double arc_sen(1:double num1),
   double cos(1:double num1),
   double arc_cos(1:double num1),
   double tan(1:double num1),
   double arc_tan(1:double num1),
}
